"use client";

import { ChevronRight, MoreHorizontal, Plus, Search, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { AppData, Student } from "@/lib/types";

export function StudentsView({ data, search, setSearch, onAdd, onEdit, onSelect }: { data: AppData; search: string; setSearch: (value: string) => void; onAdd: () => void; onEdit: (student: Student) => void; onSelect: (id: string) => void }) {
  const students = data.students.filter((student) => student.name.toLowerCase().includes(search.toLowerCase()));
  return <div className="view-stack"><div className="page-heading"><div><span className="section-kicker">DANH BẠ</span><h2>Học sinh</h2><p>{data.students.filter((student) => student.active).length} học sinh đang học</p></div><Button size="icon" className="rounded-2xl shadow-lg shadow-indigo-200" aria-label="Thêm học sinh" onClick={onAdd}><Plus className="h-5 w-5" /></Button></div><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 z-10 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm học sinh…" className="h-12 rounded-2xl pl-10" /></div>{students.length ? <div className="student-list">{students.map((student) => { const configs = data.studentSubjects.filter((item) => item.studentId === student.id && item.active); const lessonCount = data.lessons.filter((lesson) => lesson.studentId === student.id).length; return <Card className={`student-card ${!student.active ? "inactive" : ""}`} key={student.id} onClick={() => onSelect(student.id)}><span className="avatar">{student.name.charAt(0)}</span><div className="student-card-main"><div className="student-name-line"><strong>{student.name}</strong>{!student.active && <Badge variant="outline">Đã nghỉ</Badge>}</div><span>{configs.length ? configs.map((config) => data.subjects.find((subject) => subject.id === config.subjectId)?.name).filter(Boolean).join(" · ") : "Chưa gán môn học"}</span><Badge variant="secondary" className="mt-2 w-fit border-0 text-[9px]">{lessonCount} buổi đã ghi nhận</Badge></div><Button type="button" variant="ghost" size="icon" className="h-9 w-9 shrink-0 rounded-xl" aria-label="Chỉnh sửa học sinh" onClick={(event) => { event.stopPropagation(); onEdit(student); }}><MoreHorizontal className="h-4 w-4" /></Button><ChevronRight className="chevron" size={18} /></Card>; })}</div> : <div className="empty-card"><div className="empty-illustration"><Users size={27} /></div><h4>Chưa có học sinh</h4><p>Thêm học sinh và thiết lập học phí theo từng môn để bắt đầu.</p><Button type="button" variant="secondary" onClick={onAdd} className="rounded-xl"><Plus className="h-4 w-4" /> Thêm học sinh</Button></div>}</div>;
}
