"use client";

import { AlertTriangle, Check, FileText, Phone, Save, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ModalShell } from "@/components/shared/ModalShell";
import { Field } from "@/components/shared/Field";
import { AppData, Student, StudentDraft } from "@/lib/types";
import { moneyInputValue } from "@/lib/utils";

export function StudentModal({ data, initial, draft, setDraft, onClose, onSave }: { data: AppData; initial: Student | null; draft: StudentDraft; setDraft: React.Dispatch<React.SetStateAction<StudentDraft>>; onClose: () => void; onSave: () => void }) {
  const availableSubjects = data.subjects.filter((subject) => subject.active || Boolean(draft.assignments[subject.id]));
  const update = (field: keyof Omit<StudentDraft, "assignments">, value: string) => setDraft((current) => ({ ...current, [field]: value }));
  const toggle = (subjectId: string) => setDraft((current) => ({ ...current, assignments: { ...current.assignments, [subjectId]: { ...(current.assignments[subjectId] ?? { fee: 150000, duration: 90 }), active: !current.assignments[subjectId]?.active } } }));
  const updateAssignment = (subjectId: string, field: "fee" | "duration", value: string) => setDraft((current) => ({ ...current, assignments: { ...current.assignments, [subjectId]: { ...(current.assignments[subjectId] ?? { active: true, fee: 150000, duration: 90 }), [field]: Number(value) } } }));
  return <ModalShell title={initial ? "Chỉnh sửa học sinh" : "Thêm học sinh"} subtitle="Thông tin và cấu hình học phí" onClose={onClose} wide><div className="modal-form"><div className="form-section-label">THÔNG TIN CƠ BẢN</div><Field label="Tên học sinh" icon={<UserRound size={16} />}><Input autoFocus value={draft.name} onChange={(event) => update("name", event.target.value)} placeholder="Ví dụ: Minh Anh" /></Field><div className="form-grid"><Field label="Số điện thoại" icon={<Phone size={16} />}><Input value={draft.phone} onChange={(event) => update("phone", event.target.value)} placeholder="Không bắt buộc" /></Field><Field label="Tên phụ huynh" icon={<UserRound size={16} />}><Input value={draft.parentName} onChange={(event) => update("parentName", event.target.value)} placeholder="Không bắt buộc" /></Field></div><Field label="Số điện thoại phụ huynh" icon={<Phone size={16} />}><Input value={draft.parentPhone} onChange={(event) => update("parentPhone", event.target.value)} placeholder="Không bắt buộc" /></Field><Field label="Ghi chú" icon={<FileText size={16} />}><Textarea rows={2} value={draft.note} onChange={(event) => update("note", event.target.value)} placeholder="Ghi chú thêm về học sinh…" /></Field><div className="form-section-label subject-form-label">MÔN HỌC & HỌC PHÍ</div><p className="form-description">Chọn môn đang học và thiết lập mức mặc định cho mỗi buổi.</p>{availableSubjects.length ? <div className="assignment-list">{availableSubjects.map((subject) => { const assignment = draft.assignments[subject.id]; return <div className={`assignment-row ${assignment?.active ? "selected" : ""}`} key={subject.id}><button className={`checkbox ${assignment?.active ? "checked" : ""}`} onClick={() => toggle(subject.id)}>{assignment?.active && <Check size={13} />}</button><div className="assignment-main"><strong>{subject.name}</strong>{!subject.active && <Badge variant="outline">Đã tạm ngưng</Badge>}</div>{assignment?.active && <div className="assignment-inputs"><label><span>đ / buổi</span><input type="number" min="0" step="1000" value={moneyInputValue(assignment.fee)} onChange={(event) => updateAssignment(subject.id, "fee", event.target.value)} /></label><label><span>phút</span><input type="number" min="1" step="5" value={assignment.duration || ""} onChange={(event) => updateAssignment(subject.id, "duration", event.target.value)} /></label></div>}</div>; })}</div> : <div className="form-alert"><AlertTriangle size={16} /> Chưa có môn học hoạt động. Hãy tạo môn trong phần Cài đặt.</div>}</div><div className="modal-footer"><Button type="button" variant="ghost" onClick={onClose}>Hủy</Button><Button type="button" onClick={onSave} className="rounded-xl"><Save className="h-4 w-4" /> Lưu hồ sơ</Button></div></ModalShell>;
}
